Document: mingw-w64-glib2
Title: Debian mingw-w64-glib2 Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-glib2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-glib2/mingw-w64-glib2.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-glib2/mingw-w64-glib2.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-glib2/mingw-w64-glib2.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-glib2/html/index.html
Files: /usr/share/doc/mingw-w64-glib2/html/*.html
